name: Azure PowerShell Deployment

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure PowerShell
      uses: azure/login@v1
      with:
        creds: |
          ${{ secrets.AZURE_CLIENT_ID }}
          ${{ secrets.AZURE_CLIENT_SECRET }}
          ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ${{ secrets.AZURE_TENANT_ID }}

    - name: Run Azure Deployment Script
      run: |
        # Run the masterscript.ps1 file located in the root of the repository
        ./masterscript.ps1      

    - name: Logout Azure PowerShell
      run: |
        az logout
