name: Azure PowerShell Deployment

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Azure PowerShell
      run: |
        Install-Module -Name Az -Force -AllowClobber

    - name: Uninstall AzureRM Module
      run: |
        Uninstall-Module -Name AzureRM -Force


    - name: Set up Azure PowerShell
      uses: azure/login@v1
      with:
        creds: |
          ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Execution Policy
      run: |
        Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force

    - name: Run Azure Deployment Script
      run: |
        # Import the Azure PowerShell module
        Import-Module -Name Az

        # Authenticate with Azure
        Connect-AzAccount

        # Run the masterscript.ps1 file
        .\masterscript.ps1

    - name: Logout Azure PowerShell
      run: |
        az logout
