name: Azure PowerShell Deployment

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3
      
    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSession: true

    - name: Export Azure Credentials
      run: 
        # Set the 'AZURE_CREDENTIALS' secret as an environment variable
        export AZURE_CREDENTIALS='${{ secrets.AZURE_CREDENTIALS }}'

    - name: Run Azure PowerShell Deployment Script
      uses: azure/powershell@v1
      with:
        inlineScript: ./masterscript.ps1
        azPSVersion: "latest"

    - name: Logout Azure PowerShell
      run: |
        az logout
